version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    container_name: health-mate-api
    ports:
      - 8080:8080
    depends_on:
      - pg
    volumes:
      - .:/app
    env_file:
      - .env

  pg:
    image: postgres:alpine
    container_name: pg
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
