FROM golang:alpine

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /app

RUN go get -u github.com/cosmtrek/air

COPY go.mod .
COPY go.sum .
RUN go mod download

CMD ["air", "-c", ".air.toml"]