version: '3'
services:
  app:
    build: .
    restart: always
    container_name: health-mate-api
    depends_on:
      - pg
    ports:
      - 8080:8080
    env_file:
      - .env

  pg:
    image: postgres:alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
