name: main

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Download Dependencies
        run: go mod download

      - name: Test
        run: |
          export PREDICT_API_URL=${{ secrets.PREDICT_API_URL }}
          go test -v ./...
